name: bloc_zero_to_hero
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:

  bloc: ^8.1.1
  
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  

dev_dependencies:
  bloc_test: ^9.1.1
  test: ^1.22.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
